### ISSUE TITLE
Maps API research

### ISSUE THREAD

**Issue by laurencecnerual** [cc-pet-sitter/backend#1]

**Comment by miwhipps** [comment]
Tutorial here for adding cards to map: https://dev.to/alex1998dmit/how-to-create-map-like-in-airbnb-with-react-and-google-maps-28i3

YouTube playlist with lots of how to's on using the Maps JavaScript API: https://www.youtube.com/watch?v=PfZ4oLftItk&list=PL2rFahu9sLJ2QuJaKKYDaJp0YqjFCDCtN
